/** Repeatable smoke checks using a disposable backend. No browser storage or trace exports. */
import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { once } from 'node:events'
import { createServer } from 'node:net'
import { chromium } from 'playwright'
import { fileURLToPath } from 'node:url'
import { setTimeout as delay } from 'node:timers/promises'
import { stopFixture } from './fixture-process.mjs'
import { selectOption, reloadList } from './ui-controls.mjs'
import { verifyQuotaReferences } from './verify-quota-references.mjs'
import { verifyListRefresh } from './verify-list-refresh.mjs'
import { verifySidebar } from './verify-sidebar.mjs'
import { verifyPublicDocs } from './help-flows.mjs'
import { fixtureContext } from './update-fixture.mjs'
import { verifyCookieAuthorization } from './verify-cookie-authorization.mjs'

const root = fileURLToPath(new URL('../../', import.meta.url))
const portProbe = createServer()
portProbe.listen(0, '127.0.0.1'); await once(portProbe, 'listening')
const port = portProbe.address().port
await new Promise(resolve => portProbe.close(resolve))
const origin = `http://127.0.0.1:${port}`
const backend = spawn('uv', ['run', '--frozen', 'python', 'dev/preview-v2.py', '--port', String(port), '--parent-pipe'], { cwd: root, stdio: ['pipe', 'pipe', 'pipe'] })
let backendErrors = ''
backend.stderr.on('data', data => { backendErrors += data.toString() })
backend.stdout.resume()
let browser
const errors = []
async function visible(locator) { await locator.waitFor({ state: 'visible', timeout: 12000 }) }
async function click(page, name) { if (name === '重载列表') return reloadList(page); await page.getByRole('button', { name, exact: true }).click() }
async function login(page, who) {
  await page.goto(origin)
  await page.getByRole('textbox', { name: '登录邮箱', exact: true }).fill(`${who}@example.test`)
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('Preview password 42!')
  await click(page, '登录')
  await visible(page.getByRole('heading', { name: '账号与额度', exact: true }))
}
async function team(page) {
  await selectOption(page, '当前空间', '团队 · Studio 开发组')
}
async function waitRows(page, count) {
  for (let attempt = 0; attempt < 80; attempt++) { if (await page.locator('[data-account]').count() === count) return; await delay(50) }
  assert.equal(await page.locator('[data-account]').count(), count)
}
try {
  for (let attempt = 0; attempt < 100; attempt++) {
    if (backend.exitCode !== null) throw new Error(`Preview failed: ${backendErrors}`)
    try { if ((await fetch(origin + '/api/v1/health')).ok) break } catch {}
    await delay(200)
  }
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHANNEL ? { channel: process.env.PLAYWRIGHT_CHANNEL } : {}) })
  const ownerContext = await fixtureContext(browser, { viewport: { width: 1440, height: 960 } })
  const owner = await ownerContext.newPage(); owner.on('pageerror', error => errors.push(error.message))
  await verifyPublicDocs(owner, origin)
  await owner.goto(origin)
  await owner.getByLabel('登录邮箱', { exact: true }).fill('owner@example.test')
  await owner.getByLabel('密码', { exact: true }).fill('Wrong preview password')
  await click(owner, '显示密码')
  assert.equal(await owner.getByLabel('密码', { exact: true }).getAttribute('type'), 'text')
  await click(owner, '隐藏密码')
  assert.equal(await owner.getByLabel('密码', { exact: true }).getAttribute('type'), 'password')
  await click(owner, '登录')
  await visible(owner.getByRole('alert'))
  assert.equal(await owner.getByRole('alert').innerText(), '登录邮箱或密码不正确。')
  assert.equal(await owner.getByLabel('密码', { exact: true }).inputValue(), '')
  assert.equal(await owner.getByLabel('登录邮箱', { exact: true }).inputValue(), 'owner@example.test')
  await login(owner, 'owner')
  await waitRows(owner, 2)
  await verifyCookieAuthorization(owner)
  // Unknown error codes and arbitrary server details must retain the generic message.
  const authorizationPattern = '**/api/v1/workspaces/*/accounts'
  await owner.route(authorizationPattern, route => route.request().method() === 'POST'
    ? route.fulfill({ status: 422, json: { code: 'constructor', detail: '<b>synthetic-server-secret</b>' } })
    : route.continue())
  await click(owner, '＋ 添加账号')
  await owner.getByLabel('Cursor 网页会话 Cookie').fill('synthetic-invalid-cookie')
  await click(owner, '保存')
  await visible(owner.getByRole('alert'))
  assert.equal(await owner.getByRole('alert').innerText(), '请检查填写的内容。')
  await click(owner, '取消')
  await owner.unroute(authorizationPattern)
  let listReads = 0
  owner.on('request', request => { if (/\/api\/v1\/workspaces\/[^/]+\/accounts\?/.test(request.url())) listReads++ })
  await verifyListRefresh(owner, () => listReads)
  await verifyQuotaReferences(owner)
  await verifySidebar(owner)
  // No visible pagination: fetch beyond the API batch limit and sort/search the complete list.
  assert.equal(await owner.locator('.accounts-content .filter-bar, .accounts-content .pagination, .card-footer').count(), 0)
  const batches = [], manyPattern = '**/api/v1/workspaces/*/accounts?*'
  let manyAccounts
  await owner.route(manyPattern, async route => {
    const params = new URL(route.request().url()).searchParams
    const response = await route.fetch(), result = await response.json()
    manyAccounts ||= Array.from({ length: 205 }, (_, index) => ({ ...result.items[0], id: 'batch-' + index, label: '批量账号 ' + String(205 - index).padStart(3, '0') }))
    const filtered = manyAccounts.filter(account => account.label.includes(params.get('q') || ''))
    const offset = Number(params.get('offset') || 0), limit = Number(params.get('limit'))
    batches.push(offset)
    await route.fulfill({ response, json: { ...result, items: filtered.slice(offset, offset + limit), total: filtered.length, offset, limit } })
  })
  await click(owner, '重载列表'); await waitRows(owner, 205)
  assert.deepEqual(batches, [0, 200])
  await selectOption(owner, '账号排序', '名称顺序')
  assert.equal(await owner.locator('[data-account] h2').first().innerText(), '批量账号 001')
  await owner.getByLabel('搜索账号').fill('批量账号 001'); await waitRows(owner, 1)
  assert.equal(await owner.locator('[data-account] h2').innerText(), '批量账号 001')
  await owner.unroute(manyPattern)
  await owner.getByRole('button', { name: '清空搜索', exact: true }).click(); await waitRows(owner, 2)
  await selectOption(owner, '账号排序', '默认顺序')
  // Shared V1 selects: real top-layer menu, keyboard navigation, focus and dismissal.
  assert.equal(await owner.locator('select').count(), 0)
  const sort = owner.getByRole('combobox', { name: '账号排序', exact: true })
  const sortMenu = owner.getByRole('listbox', { name: '账号排序', exact: true })
  await sort.click()
  assert.equal(await sortMenu.evaluate(el => el.matches(':popover-open')), true)
  assert.match(await sortMenu.evaluate(el => getComputedStyle(el).backdropFilter), /blur\(30px\)/)
  assert.equal(await sortMenu.getByRole('option', { selected: true }).innerText(), '默认顺序')
  await sort.press('ArrowDown')
  await sort.press('Enter')
  assert.equal(await sort.innerText(), '名称顺序')
  assert.equal(await sort.evaluate(el => el === document.activeElement), true)
  const labels = await owner.locator('.account-card h2').allTextContents()
  assert.deepEqual(labels, [...labels].sort((a, b) => a.localeCompare(b, 'zh-CN', { numeric: true })))
  await sort.press(' '); await sort.press('End'); await sort.press('Escape')
  assert.equal(await sort.innerText(), '名称顺序')
  assert.equal(await sort.getAttribute('aria-expanded'), 'false')
  await sort.click(); await owner.getByRole('heading', { name: '账号与额度', exact: true }).click()
  assert.equal(await sort.getAttribute('aria-expanded'), 'false')
  await sort.click(); await owner.getByRole('combobox', { name: '当前空间', exact: true }).click()
  assert.equal(await owner.locator('.ui-select-menu:popover-open').count(), 1)
  assert.equal(await sort.getAttribute('aria-expanded'), 'false')
  await owner.keyboard.press('Escape')
  await sort.focus(); await sort.press('/'); await sort.press('Escape')
  assert.equal(await sort.evaluate(el => el === document.activeElement), true)
  await selectOption(owner, '账号排序', '默认顺序')
  await owner.getByRole('complementary').getByRole('button', { name: '开发 1', exact: true }).click(); await waitRows(owner, 1)
  await owner.getByRole('complementary').getByRole('button', { name: '全部标签 2', exact: true }).click(); await waitRows(owner, 2)
  assert.match(await owner.locator('[data-account]').first().innerText(), /68%/)
  const first = owner.locator('[data-account]').first()
  // V1 hover hints and menus remain usable while crossing from the trigger into the popup.
  await first.getByRole('button', { name: '明细', exact: true }).hover()
  await visible(owner.getByRole('tooltip').filter({ hasText: '额度明细' }))
  await first.getByRole('button', { name: '更多账号操作', exact: true }).hover()
  const accountMenu = first.getByRole('dialog', { name: '账号操作', exact: true })
  await visible(accountMenu)
  await accountMenu.getByRole('button', { name: '编辑资料与标签', exact: true }).hover()
  assert.equal(await accountMenu.isVisible(), true)
  assert.equal(await accountMenu.locator('button > svg').count(), 3)
  await owner.getByRole('heading', { name: '账号与额度', exact: true }).hover()
  await accountMenu.waitFor({ state: 'hidden' })
  await first.getByRole('button', { name: '更多账号操作', exact: true }).focus()
  await owner.keyboard.press('ArrowDown')
  await visible(accountMenu)
  assert.equal(await accountMenu.getByRole('button', { name: '编辑资料与标签' }).evaluate(el => el === document.activeElement), true)
  await owner.keyboard.press('Escape'); await accountMenu.waitFor({ state: 'hidden' })
  const spendHint = first.getByRole('button', { name: '本周期消费', exact: true })
  await spendHint.hover()
  await visible(owner.getByRole('tooltip').filter({ hasText: '本周期两类模型额度的合计上限' }))
  assert.match(await spendHint.evaluate(el => getComputedStyle(el).textDecorationStyle), /wavy/)
  await first.getByRole('button', { name: 'Grok Bot 周额度', exact: true }).hover()
  const grokHint = owner.getByRole('dialog', { name: 'Grok Bot 周额度说明', exact: true })
  await visible(grokHint)
  const download = grokHint.getByRole('link')
  await download.hover()
  assert.equal(await download.getAttribute('href'), 'https://cursor.com/download/bot')
  await download.focus(); await owner.keyboard.press('Escape')
  await grokHint.waitFor({ state: 'hidden' })
  await first.getByRole('button', { name: '明细', exact: true }).click()
  await visible(owner.getByText('Claude Sonnet', { exact: true }))
  assert.match(await owner.getByRole('dialog').evaluate(el => getComputedStyle(el).backdropFilter), /blur\(30px\)/)
  assert.match(await owner.getByRole('dialog').evaluate(el => getComputedStyle(el, '::backdrop').backdropFilter), /blur\(6px\)/)
  assert.equal(await owner.getByRole('table').count(), 2)
  await visible(owner.getByText('285,000', { exact: true }))
  await owner.keyboard.press('Escape')
  assert.equal(await owner.getByRole('dialog').count(), 0)
  assert.equal(await first.getByRole('button', { name: '明细', exact: true }).evaluate(el => el === document.activeElement), true)
  assert.equal(await owner.evaluate(() => document.body.style.overflow), '')

  // V1 card presentation retains upstream quota semantics and independent skin/theme controls.
  assert.deepEqual(await owner.evaluate(() => ({ ...document.documentElement.dataset })), { skin: 'glass', theme: 'dark' })
  assert.equal(await first.getByRole('progressbar').count(), 3)
  assert.equal(await first.getByRole('progressbar', { name: '综合已用额度', exact: true }).getAttribute('aria-valuenow'), '32')
  await click(owner, '显示偏好'); await click(owner, '浅色'); await click(owner, '经典')
  assert.equal(await owner.evaluate(() => document.documentElement.dataset.theme), 'light')
  assert.equal(await owner.evaluate(() => getComputedStyle(document.body, '::before').backgroundImage), 'none')
  await click(owner, '液态玻璃'); await click(owner, '深色'); await click(owner, '关闭显示偏好')
  const searchBefore = await owner.locator('.search-field').boundingBox()
  const sortBefore = await sort.boundingBox()
  await owner.keyboard.press('/')
  assert.equal(await owner.getByLabel('搜索账号').evaluate(el => el === document.activeElement), true)
  await owner.waitForFunction(() => Math.abs(document.querySelector('.search-field').getBoundingClientRect().width - document.querySelector('.search-wrap').getBoundingClientRect().width) < 1)
  assert.ok((await owner.locator('.search-field').boundingBox()).width > searchBefore.width + 30)
  assert.equal((await sort.boundingBox()).x, sortBefore.x)
  await owner.getByLabel('搜索账号').fill('没有这个账号'); await waitRows(owner, 0)
  await owner.getByRole('button', { name: '清空搜索', exact: true }).click(); await waitRows(owner, 2)
  assert.equal(await owner.getByLabel('搜索账号').inputValue(), '')
  assert.equal(await owner.getByLabel('搜索账号').evaluate(el => el === document.activeElement), true)
  await first.getByRole('button', { name: '查看Cursor Models明细', exact: true }).click()
  await visible(owner.getByRole('dialog'))
  await visible(owner.getByText('Composer', { exact: true }))
  assert.equal(await owner.getByText('Claude Sonnet', { exact: true }).count(), 0)
  await owner.getByRole('button', { name: '查看Other Models', exact: true }).click()
  await visible(owner.getByText('Claude Sonnet', { exact: true }))
  assert.equal(await owner.getByText('Composer', { exact: true }).count(), 0)
  await owner.mouse.click(10, 10)
  await owner.getByRole('dialog').waitFor({ state: 'detached' })
  assert.equal(await first.getByRole('button', { name: '查看Cursor Models明细', exact: true }).evaluate(el => el === document.activeElement), true)
  await click(owner, '显示偏好'); await click(owner, '卡片显示项'); await owner.getByLabel('按量付费', { exact: true }).uncheck(); await click(owner, '完成')
  assert.equal(await first.locator('.card-meta').getByText('按量付费', { exact: true }).count(), 0)
  await owner.reload(); await waitRows(owner, 2)
  assert.equal(await first.locator('.card-meta').getByText('按量付费', { exact: true }).count(), 0)
  await click(owner, '显示偏好'); await click(owner, '卡片显示项'); await owner.getByLabel('按量付费', { exact: true }).check(); await click(owner, '完成')

  // Upgrading an eight-option preference keeps saved choices and enables the missing identity fields.
  await owner.evaluate(() => localStorage.setItem('cursor.v2.cards', JSON.stringify({ ribbon: true, ring: true, watermark: true, stats: true, reset: true, spend: true, onDemand: false, grok: true })))
  await owner.reload(); await waitRows(owner, 2)
  await click(owner, '显示偏好'); await click(owner, '卡片显示项')
  const display = owner.getByRole('dialog', { name: '卡片显示项', exact: true })
  assert.equal(await display.getByRole('checkbox').count(), 12)
  assert.equal(await display.getByRole('status').innerText(), '11/12 开启')
  assert.deepEqual(await display.locator('.display-section-heading > span').allTextContents(), ['3/3', '4/4', '4/5'])
  for (const label of ['套餐徽章', '部门标记', '邮箱', '额度上限']) {
    assert.equal(await display.getByLabel(label, { exact: true }).isChecked(), true)
    await display.getByLabel(label, { exact: true }).uncheck()
  }
  await click(owner, '完成')
  await owner.reload(); await waitRows(owner, 2)
  assert.equal(await first.locator('.plan, .department-mark, .account-email, .quota-limit, .account-identity-line').count(), 0)
  assert.equal(await first.getByRole('progressbar').count(), 3)
  await owner.getByLabel('搜索账号').fill('preview0@example.test'); await waitRows(owner, 1)
  assert.equal(await first.locator('.account-email').count(), 0)
  await owner.getByRole('button', { name: '清空搜索', exact: true }).click(); await waitRows(owner, 2)
  await first.getByRole('button', { name: '明细', exact: true }).click()
  assert.equal(await owner.getByRole('dialog').locator('.quota-limit').count(), 3)
  await owner.keyboard.press('Escape')
  await click(owner, '显示偏好'); await click(owner, '卡片显示项'); await click(owner, '精简')
  assert.equal(await display.getByRole('status').innerText(), '5/12 开启')
  await click(owner, '完成')
  assert.equal(await first.locator('.card-meta > div').count(), 2)
  assert.equal(await first.locator('.plan, .department-mark').count(), 2)
  assert.equal(await first.locator('.cycle-ring, .account-email, .quota-limit').count(), 0)
  await click(owner, '显示偏好'); await click(owner, '卡片显示项'); await click(owner, '恢复默认')
  assert.equal(await display.getByRole('status').innerText(), '12/12 开启')
  assert.equal(await display.getByLabel('按量付费', { exact: true }).isChecked(), true)
  await owner.screenshot({ path: fileURLToPath(new URL('../../output/playwright/card-display-glass.png', import.meta.url)), animations: 'disabled' })
  await click(owner, '精简'); await click(owner, '全开')
  assert.equal(await display.getByRole('status').innerText(), '12/12 开启')
  await owner.setViewportSize({ width: 390, height: 844 })
  const displayBounds = await display.boundingBox()
  assert.ok(displayBounds.x >= 0 && displayBounds.x + displayBounds.width <= 390)
  assert.equal(await display.locator('.dialog-body').evaluate(el => el.scrollWidth <= el.clientWidth), true)
  assert.equal(await display.getByRole('button', { name: '完成', exact: true }).isVisible(), true)
  await owner.screenshot({ path: fileURLToPath(new URL('../../output/playwright/card-display-mobile.png', import.meta.url)), animations: 'disabled' })
  await click(owner, '完成'); await owner.setViewportSize({ width: 1440, height: 960 })
  await owner.evaluate(() => {
    localStorage.removeItem('cursor.v2.cards')
    localStorage.setItem('panelCardPrefs', JSON.stringify({ cycleRing: false, statTime: false, email: false, limit: false, plan: 'invalid' }))
  })
  await owner.reload(); await waitRows(owner, 2)
  assert.equal(await first.locator('.cycle-ring, .account-email, .quota-limit').count(), 0)
  assert.equal(await first.getByText('最后统计', { exact: true }).count(), 0)
  assert.equal(await first.locator('.plan').count(), 1)
  await click(owner, '显示偏好'); await click(owner, '卡片显示项'); await click(owner, '恢复默认'); await click(owner, '完成')

  // A held refresh must visibly replace only that card's data, without moving the grid.
  const refreshPattern = '**/api/v1/workspaces/*/accounts/*/refresh'
  let releaseRefresh
  const refreshGate = new Promise(resolve => { releaseRefresh = resolve })
  await owner.route(refreshPattern, async route => { await refreshGate; await route.continue() })
  const beforeRefresh = await first.boundingBox()
  const neighbor = owner.locator('[data-account]').nth(1)
  const neighborText = await neighbor.innerText(), neighborBounds = await neighbor.boundingBox()
  const refreshButton = first.getByRole('button', { name: '刷新', exact: true })
  await refreshButton.focus(); await refreshButton.click()
  await visible(first.locator('.card-refresh-skeleton'))
  assert.equal(await first.getAttribute('aria-busy'), 'true')
  assert.equal(await first.getByRole('progressbar').count(), 0)
  assert.equal(await first.getByRole('button').count(), 0)
  assert.equal(await first.locator('.account-email').isVisible(), true)
  assert.ok(Math.abs((await first.boundingBox()).height - beforeRefresh.height) < 1)
  assert.deepEqual(await neighbor.boundingBox(), neighborBounds)
  assert.equal(await neighbor.innerText(), neighborText)
  assert.equal(await neighbor.locator('.card-refresh-skeleton').count(), 0)
  await owner.screenshot({ path: fileURLToPath(new URL('../../output/playwright/card-refresh-skeleton.png', import.meta.url)), animations: 'disabled' })
  await owner.emulateMedia({ reducedMotion: 'reduce' })
  assert.equal(await first.locator('.card-skeleton-line').first().evaluate(el => getComputedStyle(el).animationName), 'none')
  await owner.emulateMedia({ reducedMotion: 'no-preference' })
  releaseRefresh()
  await first.locator('.card-refresh-skeleton').waitFor({ state: 'detached' })
  await owner.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === '刷新')
  assert.equal(await first.getByRole('progressbar').count(), 3)
  await owner.unroute(refreshPattern)
  const lastQuota = await first.getByRole('progressbar').first().getAttribute('aria-valuenow')
  await owner.route(refreshPattern, route => route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }))
  await refreshButton.click()
  await visible(first.getByRole('alert'))
  assert.match(await first.getByRole('alert').innerText(), /刷新失败，已保留上次数据/)
  assert.equal(await first.locator('.card-refresh-skeleton').count(), 0)
  assert.equal(await first.getByRole('progressbar').first().getAttribute('aria-valuenow'), lastQuota)
  await owner.unroute(refreshPattern)
  await refreshButton.click()
  await first.locator('.card-refresh-skeleton').waitFor({ state: 'detached' })
  assert.equal(await first.getByRole('alert').count(), 0)

  // Exhausted/unknown snapshots must not invent a remaining balance or billing cycle.
  const listPattern = '**/api/v1/workspaces/*/accounts?*'
  await owner.route(listPattern, async route => {
    const response = await route.fetch()
    const result = await response.json()
    result.items[0].data.quota.overall = { remaining_pct: 0, used_pct: 100, limit_inferred: true }
    result.items[1].data = null; result.items[1].pending = true; result.items[1].ok_at = 0
    await route.fulfill({ response, json: result })
  })
  await click(owner, '重载列表')
  await visible(first.locator('.burnout-watermark'))
  assert.equal(await first.getByRole('progressbar', { name: '综合已用额度', exact: true }).getAttribute('aria-valuenow'), '100')
  const pending = owner.locator('[data-account]').nth(1)
  assert.equal(await pending.locator('.ribbon, .cycle-ring').count(), 0)
  assert.equal(await pending.getByRole('progressbar').first().getAttribute('aria-valuenow'), null)
  await visible(pending.getByText('等待首次刷新', { exact: true }).first())
  await owner.unroute(listPattern); await click(owner, '重载列表')
  await first.locator('.burnout-watermark').waitFor({ state: 'detached' })

  // Closing an in-flight detail cannot repaint after an unrelated space is selected.
  let releaseDetail
  let enteredDetail
  const entered = new Promise(resolve => { enteredDetail = resolve })
  await owner.route('**/api/v1/workspaces/*/accounts/*/detail', async route => {
    const response = await route.fetch(); enteredDetail()
    await new Promise(resolve => { releaseDetail = resolve })
    await route.fulfill({ response }).catch(() => {})
  })
  await first.getByRole('button', { name: '明细', exact: true }).click()
  await entered
  await owner.keyboard.press('Escape'); await team(owner)
  releaseDetail(); await owner.unroute('**/api/v1/workspaces/*/accounts/*/detail')
  await waitRows(owner, 3)
  assert.equal(await owner.getByRole('dialog').count(), 0)

  const memberContext = await fixtureContext(browser)
  const member = await memberContext.newPage(); member.on('pageerror', error => errors.push(error.message))
  await login(member, 'member'); await waitRows(member, 0); await team(member); await waitRows(member, 1)
  assert.equal(await member.getByRole('button', { name: '＋ 添加账号', exact: true }).count(), 0)
  assert.equal(await member.getByRole('button', { name: '切换', exact: true }).count(), 1)
  assert.equal(await member.getByRole('button', { name: '刷新', exact: true }).count(), 1)

  const viewerContext = await fixtureContext(browser)
  const viewer = await viewerContext.newPage()
  await login(viewer, 'viewer'); await team(viewer); await waitRows(viewer, 0)
  await visible(viewer.getByRole('heading', { name: '这里还没有可见账号' }))

  // Owner can grant a single account; viewer gets read-only controls.
  const shared = owner.locator('[data-account]').filter({ has: owner.getByRole('heading', { name: '团队主账号', exact: true }) })
  await shared.getByLabel('更多账号操作').click()
  await shared.getByRole('button', { name: '账号授权', exact: true }).click()
  await visible(owner.getByRole('dialog'))
  const permission = owner.getByRole('combobox', { name: 'viewer@example.test的账号权限', exact: true })
  await permission.click()
  assert.equal(await owner.getByRole('listbox').getByRole('option', { name: '使用', exact: true }).count(), 0)
  await owner.keyboard.press('Escape')
  await visible(owner.getByRole('dialog'))
  assert.equal(await permission.evaluate(el => el === document.activeElement), true)
  // Failed writes retain the server's selection; pending writes disable every grant control.
  let releaseGrant
  const pendingGrant = new Promise(resolve => { releaseGrant = resolve })
  await owner.route('**/api/v1/workspaces/*/accounts/*/grants/*', async route => {
    await pendingGrant
    await route.fulfill({ status: 503, json: { detail: 'preview unavailable' } })
  })
  await selectOption(owner, 'viewer@example.test的账号权限', '查看')
  await owner.waitForFunction(() => [...document.querySelectorAll('dialog [role=combobox]')].every(el => el.disabled))
  releaseGrant()
  await visible(owner.getByRole('dialog').getByRole('alert'))
  assert.equal(await permission.innerText(), '无权限')
  await owner.unroute('**/api/v1/workspaces/*/accounts/*/grants/*')
  await Promise.all([
    owner.waitForResponse(response => response.url().endsWith('/grants') && response.request().method() === 'GET'),
    selectOption(owner, 'viewer@example.test的账号权限', '查看'),
  ])
  await owner.keyboard.press('Escape')
  await click(viewer, '重载列表'); await waitRows(viewer, 1)
  assert.equal(await viewer.getByRole('button', { name: '切换', exact: true }).count(), 0)
  assert.equal(await viewer.getByRole('button', { name: '刷新', exact: true }).count(), 0)
  await viewer.getByLabel('搜索账号').fill('设计协作'); await waitRows(viewer, 0)
  await visible(viewer.getByRole('heading', { name: '没有匹配的账号' }))

  // The browser receives a short command; its single-use download needs no browser session.
  await click(member, '切换')
  const platform = member.getByRole('combobox', { name: '操作系统', exact: true })
  await platform.focus(); await platform.press('w'); await platform.press('Enter')
  assert.equal(await platform.innerText(), 'Windows · PowerShell')
  await platform.click(); await platform.press('Tab')
  assert.equal(await platform.getAttribute('aria-expanded'), 'false')
  assert.equal(await member.getByRole('checkbox').evaluate(el => el === document.activeElement), true)
  await selectOption(member, '操作系统', 'macOS · 终端')
  await member.getByRole('checkbox').check()
  await click(member, '生成终端命令')
  await visible(member.getByLabel('切换命令'))
  const switchCommand = await member.getByLabel('切换命令').inputValue()
  assert.ok(switchCommand.length < 400)
  assert.ok(switchCommand.includes('curl -fsS'))
  assert.ok(!switchCommand.includes('base64'))
  const downloadUrl = switchCommand.match(/http:\/\/[^\s'")]+/)[0]
  const downloaded = await fetch(downloadUrl)
  assert.equal(downloaded.status, 200)
  assert.ok((await downloaded.text()).startsWith('exit 1 # 仅供预览'))
  assert.equal((await fetch(downloadUrl)).status, 404)
  await member.keyboard.press('Escape')
  assert.equal(await member.getByLabel('切换命令').count(), 0)

  // Add/rename/tag/reauthorize/delete with provider fixture and escaped labels.
  await click(owner, '＋ 添加账号')
  await owner.getByLabel('账号名称').fill('<b>验证账号</b>')
  await owner.getByRole('button', { name: '标签', exact: true }).click()
  const tagPicker = owner.getByRole('dialog', { name: '选择账号标签', exact: true })
  await tagPicker.getByRole('button', { name: /^开发/ }).click()
  assert.equal(await tagPicker.getByRole('button', { name: /^开发/ }).getAttribute('aria-pressed'), 'true')
  await tagPicker.getByRole('textbox', { name: '搜索或新建标签' }).fill('验证, CI')
  await tagPicker.getByRole('textbox', { name: '搜索或新建标签' }).press('Enter')
  await tagPicker.getByRole('button', { name: '完成', exact: true }).click()
  assert.equal(await owner.getByRole('dialog').count(), 1)
  assert.deepEqual(await owner.locator('.selected-account-tags .account-tag').allTextContents(), ['开发', '验证', 'CI'])
  assert.equal(await owner.getByLabel('Cursor 网页会话 Cookie').evaluate(el => el.tagName), 'TEXTAREA')
  const claims = Buffer.from(JSON.stringify({ sub: 'auth0|user_added', type: 'session', exp: Math.floor(Date.now() / 1000) + 86400 })).toString('base64url')
  await owner.getByLabel('Cursor 网页会话 Cookie').fill(`user_added::eyJhbGciOiJIUzI1NiJ9.${claims}.synthetic`)
  await click(owner, '保存')
  await waitRows(owner, 4)
  const added = owner.locator('[data-account]').filter({ has: owner.getByRole('heading', { name: '<b>验证账号</b>', exact: true }) })
  assert.equal(await added.locator('h2 b').count(), 0)
  assert.deepEqual((await added.locator('.department-mark').getAttribute('title')).split(' · ').sort(), ['开发', '验证', 'CI'].sort())
  await added.getByLabel('更多账号操作').click(); await added.getByRole('button', { name: '编辑资料与标签' }).click()
  await owner.getByLabel('账号名称').fill('已编辑账号')
  await owner.getByRole('button', { name: '标签', exact: true }).click()
  for (const tagName of ['开发', '验证', 'CI']) await tagPicker.getByRole('button', { name: new RegExp('^' + tagName + '(?: \\d+)?$') }).click()
  await tagPicker.getByRole('textbox', { name: '搜索或新建标签' }).fill('编辑验证')
  await tagPicker.getByRole('textbox', { name: '搜索或新建标签' }).press('Enter')
  await owner.keyboard.press('Escape')
  assert.equal(await owner.getByRole('dialog').count(), 1)
  await click(owner, '保存')
  await visible(owner.getByRole('heading', { name: '已编辑账号', exact: true }))
  const edited = owner.locator('[data-account]').filter({ has: owner.getByRole('heading', { name: '已编辑账号', exact: true }) })
  await edited.getByLabel('更多账号操作').click(); await edited.getByRole('button', { name: '重新授权', exact: true }).click()
  await owner.getByLabel('Cursor 网页会话 Cookie').fill(`user_added::eyJhbGciOiJIUzI1NiJ9.${claims}.synthetic`)
  await click(owner, '保存'); await owner.getByRole('dialog').waitFor({ state: 'detached' })
  await edited.getByLabel('更多账号操作').click(); await edited.getByRole('button', { name: '删除账号', exact: true }).click()
  await click(owner, '确认删除'); await waitRows(owner, 3)

  // Invite link never leaves the fragment; new identity joins with no account access.
  await owner.getByRole('link', { name: '空间设置', exact: false }).click()
  await owner.getByLabel('受邀邮箱').fill('new@example.test'); await click(owner, '创建邀请')
  await visible(owner.getByLabel('邀请链接'))
  const invitation = await owner.getByLabel('邀请链接').inputValue()
  const newContext = await fixtureContext(browser); const newcomer = await newContext.newPage()
  newcomer.on('pageerror', error => errors.push(error.message))
  await newcomer.goto(invitation)
  await visible(newcomer.getByRole('heading', { name: '加入团队空间', exact: true }))
  assert.equal(newcomer.url(), origin + '/#/join')
  assert.ok((await newcomer.getByLabel('邀请票据').inputValue()).length > 20)
  const originalTicket = await newcomer.getByLabel('邀请票据').inputValue()
  await newcomer.getByLabel('设置密码', { exact: true }).fill('Preview password 42!')
  await click(newcomer, '显示密码')
  assert.equal(await newcomer.getByLabel('设置密码', { exact: true }).getAttribute('type'), 'text')
  await click(newcomer, '隐藏密码')
  assert.equal(await newcomer.getByLabel('设置密码', { exact: true }).getAttribute('type'), 'password')
  await newcomer.getByRole('link', { name: '先登录，再接受邀请', exact: true }).click()
  await visible(newcomer.getByText('登录后继续接受团队邀请。', { exact: true }))
  await newcomer.getByRole('link', { name: '接受团队邀请', exact: true }).click()
  assert.equal(await newcomer.getByLabel('邀请票据').inputValue(), originalTicket)
  assert.equal(await newcomer.getByLabel('设置密码', { exact: true }).inputValue(), '')
  await newcomer.screenshot({ path: fileURLToPath(new URL('../../output/playwright/join-from-link.png', import.meta.url)), animations: 'disabled' })
  await newcomer.getByLabel('邀请票据').fill('invalid-invitation-ticket-42')
  await newcomer.getByLabel('设置密码', { exact: true }).fill('Preview password 42!')
  await click(newcomer, '接受邀请')
  await visible(newcomer.getByRole('alert'))
  assert.equal(await newcomer.getByLabel('设置密码', { exact: true }).inputValue(), '')
  await newcomer.getByLabel('邀请票据').fill(originalTicket)
  await newcomer.getByLabel('设置密码').fill('Preview password 42!'); await click(newcomer, '接受邀请')
  await visible(newcomer.getByRole('status'))
  assert.equal(await newcomer.getByRole('heading', { name: '邀请已接受', exact: true }).count(), 1)
  assert.equal(await newcomer.getByLabel('邀请票据').count(), 0)
  assert.equal(await newcomer.getByLabel('设置密码', { exact: true }).count(), 0)
  await newcomer.screenshot({ path: fileURLToPath(new URL('../../output/playwright/join-success.png', import.meta.url)), animations: 'disabled' })
  await login(newcomer, 'new'); await team(newcomer); await waitRows(newcomer, 0)
  await owner.keyboard.press('Escape')

  // Collaboration forms create a space and accept a full invitation link without leaving the workspace.
  const collaboration = await ownerContext.newPage()
  collaboration.on('pageerror', error => errors.push(error.message))
  await collaboration.goto(origin)
  await visible(collaboration.getByRole('heading', { name: '账号与额度', exact: true }))
  await click(collaboration, '团队协作'); await click(collaboration, '创建团队空间')
  const createDialog = collaboration.getByRole('dialog', { name: '创建团队空间', exact: true })
  await createDialog.getByLabel('空间名称', { exact: true }).fill('   ')
  await click(collaboration, '创建空间')
  await visible(createDialog.getByRole('alert'))
  await createDialog.getByLabel('空间名称', { exact: true }).fill('协作表单验证')
  await click(collaboration, '创建空间'); await createDialog.waitFor({ state: 'detached' })
  assert.match(await collaboration.getByRole('combobox', { name: '当前空间', exact: true }).innerText(), /协作表单验证/)
  await collaboration.getByRole('link', { name: '空间设置', exact: true }).click()
  await collaboration.getByLabel('受邀邮箱').fill('new@example.test'); await click(collaboration, '创建邀请')
  const teamInvitation = await collaboration.getByLabel('邀请链接').inputValue()
  await collaboration.keyboard.press('Escape')
  await newcomer.getByRole('button', { name: '团队协作', exact: true }).click()
  await click(newcomer, '接受团队邀请')
  const joinDialog = newcomer.getByRole('dialog', { name: '接受团队邀请', exact: true })
  const invitationField = joinDialog.getByLabel('邀请链接或票据', { exact: true })
  await invitationField.fill('invalid'); await click(newcomer, '接受邀请')
  await visible(joinDialog.getByRole('alert'))
  await invitationField.fill(teamInvitation); await click(newcomer, '接受邀请')
  await joinDialog.waitFor({ state: 'detached' })
  assert.match(await newcomer.getByRole('combobox', { name: '当前空间', exact: true }).innerText(), /协作表单验证/)
  assert.equal(await newcomer.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }).includes('token=')), false)
  await newcomer.getByRole('button', { name: '团队协作', exact: true }).click(); await click(newcomer, '接受团队邀请')
  assert.equal(await newcomer.getByLabel('邀请链接或票据', { exact: true }).inputValue(), '')
  await newcomer.keyboard.press('Escape')
  assert.equal(await newcomer.getByRole('button', { name: '团队协作', exact: true }).evaluate(el => el === document.activeElement), true)
  await collaboration.close()

  // Mobile reflow and keyboard access; preferences alone survive reload.
  await member.setViewportSize({ width: 390, height: 844 })
  assert.equal(await member.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  const mobileCard = member.locator('[data-account]').first()
  assert.equal(await mobileCard.locator('.card-quick-actions').evaluate(el => getComputedStyle(el).opacity), '1')
  await mobileCard.getByRole('button', { name: '明细', exact: true }).click()
  await visible(member.getByText('Claude Sonnet', { exact: true })); await member.keyboard.press('Escape')
  await click(member, '展开导航')
  await member.getByRole('link', { name: '个人设置' }).click()
  await visible(member.getByRole('heading', { name: '个人设置', exact: true })).catch(async error => { throw new Error(error.message + '\n' + member.url() + '\n' + await member.locator('body').innerText() + '\n' + errors.join('\n')) })
  assert.equal(await member.locator('main').getByRole('combobox', { name: '皮肤', exact: true }).count(), 0)
  assert.equal(await member.locator('main').getByRole('combobox', { name: '明暗', exact: true }).count(), 0)
  await click(member, '展开导航')
  await click(member, '显示偏好')
  const mobilePreferences = member.getByRole('dialog', { name: '显示偏好', exact: true })
  await mobilePreferences.getByRole('button', { name: '更多界面风格', exact: true }).press('ArrowDown')
  const mobileMenu = member.getByRole('dialog', { name: '更多界面风格', exact: true })
  const bounds = await mobileMenu.boundingBox()
  assert.ok(bounds.x >= 8 && bounds.x + bounds.width <= 382 && bounds.y >= 0 && bounds.y + bounds.height <= 844)
  await mobileMenu.getByRole('button', { name: '青野绿意', exact: true }).click()
  await mobilePreferences.getByRole('button', { name: '浅色', exact: true }).click()
  await mobilePreferences.getByRole('button', { name: '关闭显示偏好', exact: true }).click()
  await member.getByRole('button', { name: '团队协作', exact: true }).click(); await click(member, '创建团队空间')
  await visible(member.getByRole('dialog', { name: '创建团队空间', exact: true }))
  await member.keyboard.press('Escape')
  assert.equal(await member.getByRole('button', { name: '展开导航', exact: true }).evaluate(el => el === document.activeElement), true)
  assert.equal(await member.evaluate(() => document.documentElement.dataset.theme), 'light')
  const keys = await member.evaluate(() => Object.keys(localStorage))
  assert.deepEqual(keys.sort(), ['cursor.v2.skin', 'cursor.v2.theme', 'cursor.v2.updates.web'])
  const updateCache = await member.evaluate(() => JSON.parse(localStorage.getItem('cursor.v2.updates.web')))
  assert.deepEqual(Object.keys(updateCache).sort(), ['attemptedAt', 'checkedAt', 'release', 'version'])
  assert.equal(updateCache.release.available, false)
  assert.equal(await member.evaluate(() => sessionStorage.length), 0)
  await member.reload(); await visible(member.getByRole('heading', { name: '个人设置', exact: true }))
  assert.equal(await member.evaluate(() => document.documentElement.dataset.skin), 'verdant')
  assert.equal(await member.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)

  // Instance disable revokes the existing member session; the next request clears old UI.
  await owner.getByRole('link', { name: '实例设置' }).click()
  const memberRow = owner.locator('.setting-row').filter({ has: owner.getByText('member@example.test', { exact: true }) })
  await memberRow.getByRole('button', { name: '停用用户' }).click(); await click(owner, '确认')
  await owner.getByRole('dialog').waitFor({ state: 'detached' })
  await click(member, '重载会话')
  await visible(member.getByRole('heading', { name: '登录你的空间' }))
  assert.equal(await member.locator('.sidebar').count(), 0)
  assert.equal(await member.getByRole('dialog').count(), 0)

  // Unsupported API versions block the app before sending credentials.
  const incompatible = await browser.newPage()
  await incompatible.route('**/api/v1/bootstrap', route => route.fulfill({ json: { api_version: 2, mode: 'server', initialized: true, capabilities: {} } }))
  await incompatible.goto(origin)
  await visible(incompatible.getByRole('alert'))
  assert.match(await incompatible.getByRole('alert').innerText(), /版本不兼容/)
  assert.equal(await incompatible.getByLabel('密码', { exact: true }).count(), 0)
  assert.deepEqual(errors, [])
  console.log('PASS Web: login, isolated workspaces, view/use controls, detail/focus, stale request cancellation, preview script cleanup, account lifecycle, invitations, responsive layout, display-only persistence, session revocation and incompatible API')
} finally {
  await browser?.close()
  await stopFixture(backend)
}
