/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_v1_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Updates */
        get: operations["check_updates_api_v1_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instance/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Update Status */
        get: operations["update_status_api_v1_instance_update_get"];
        put?: never;
        /** Install Update */
        post: operations["install_update_api_v1_instance_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Password */
        put: operations["password_api_v1_auth_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_v1_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_api_v1_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Device */
        post: operations["approve_device_api_v1_auth_devices_authorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange Device */
        post: operations["exchange_device_api_v1_auth_devices_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_v1_auth_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/devices/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Device */
        delete: operations["revoke_device_api_v1_auth_devices__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Workspace */
        delete: operations["delete_workspace_api_v1_workspaces__workspace_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Transfer Owner */
        put: operations["transfer_owner_api_v1_workspaces__workspace_id__owner_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["members_api_v1_workspaces__workspace_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Role */
        put: operations["role_api_v1_workspaces__workspace_id__members__user_id__put"];
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_workspaces__workspace_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invitations */
        get: operations["invitations_api_v1_workspaces__workspace_id__invitations_get"];
        put?: never;
        /** Invite */
        post: operations["invite_api_v1_workspaces__workspace_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invitation */
        delete: operations["revoke_invitation_api_v1_workspaces__workspace_id__invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_v1_workspaces__workspace_id__accounts_get"];
        put?: never;
        /** Authorize Account */
        post: operations["authorize_account_api_v1_workspaces__workspace_id__accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account */
        get: operations["account_api_v1_workspaces__workspace_id__accounts__account_id__get"];
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_workspaces__workspace_id__accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Edit Account */
        patch: operations["edit_account_api_v1_workspaces__workspace_id__accounts__account_id__patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/authorization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthorize Account */
        post: operations["reauthorize_account_api_v1_workspaces__workspace_id__accounts__account_id__authorization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_workspaces__workspace_id__accounts__account_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_v1_workspaces__workspace_id__accounts__account_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grants */
        get: operations["grants_api_v1_workspaces__workspace_id__accounts__account_id__grants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/grants/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Grant */
        put: operations["grant_api_v1_workspaces__workspace_id__accounts__account_id__grants__user_id__put"];
        post?: never;
        /** Revoke Grant */
        delete: operations["revoke_grant_api_v1_workspaces__workspace_id__accounts__account_id__grants__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Audit */
        get: operations["workspace_audit_api_v1_workspaces__workspace_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instance/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_api_v1_instance_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instance/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** User State */
        put: operations["user_state_api_v1_instance_users__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instance/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance Audit */
        get: operations["instance_audit_api_v1_instance_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/manual-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Ticket */
        post: operations["manual_ticket_api_v1_workspaces__workspace_id__accounts__account_id__manual_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/switch-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Command */
        post: operations["manual_command_api_v1_workspaces__workspace_id__accounts__account_id__switch_command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/switch/{token}/{platform}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manual Download */
        get: operations["manual_download_api_v1_switch__token___platform__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manual-switch/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Consume */
        post: operations["manual_consume_api_v1_manual_switch_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/accounts/{account_id}/device-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Device Ticket */
        post: operations["device_ticket_api_v1_workspaces__workspace_id__accounts__account_id__device_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device-switch/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Device Consume */
        post: operations["device_consume_api_v1_device_switch_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device-switch/{ticket_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Device Result */
        post: operations["device_result_api_v1_device_switch__ticket_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvite */
        AcceptInvite: {
            /**
             * Token
             * Format: password
             */
            token: string;
            /** Password */
            password?: string | null;
        };
        /** AccountCapabilities */
        AccountCapabilities: {
            /** View */
            view: boolean;
            /** Detail */
            detail: boolean;
            /** Refresh */
            refresh: boolean;
            /** Switch */
            switch: boolean;
            /** Edit */
            edit: boolean;
            /** Delete */
            delete: boolean;
            /** Authorize */
            authorize: boolean;
            /** Grant */
            grant: boolean;
        };
        /** AccountEdit */
        AccountEdit: {
            /** Label */
            label?: string | null;
            /** Tags */
            tags?: string[] | null;
            quota_reference?: components["schemas"]["QuotaReference"] | null;
        };
        /** AccountPage */
        AccountPage: {
            /** Items */
            items: components["schemas"]["AccountView"][];
            /** Total */
            total: number;
            /** Tags */
            tags: {
                [key: string]: number;
            };
            stats: components["schemas"]["AccountStats"];
        };
        /** AccountStats */
        AccountStats: {
            /** Accounts */
            accounts: number;
            /** Invalid */
            invalid: number;
            /** With Snapshot */
            with_snapshot: number;
        };
        /** AccountView */
        AccountView: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Label */
            label: string;
            /** Email */
            email: string | null;
            /** Tags */
            tags: string[];
            capabilities: components["schemas"]["AccountCapabilities"];
            /** Authorization Generation */
            authorization_generation: string;
            /** Credential Version */
            credential_version: number;
            /** Auth Invalid */
            auth_invalid: boolean;
            /** Expires At */
            expires_at: number;
            /** Refreshed At */
            refreshed_at: number;
            data: components["schemas"]["Usage"] | null;
            /** Ok At */
            ok_at: number;
            /** Attempted At */
            attempted_at: number;
            /** Error Kind */
            error_kind: string | null;
            /** Error Message */
            error_message: string | null;
            /** Failures */
            failures: number;
            /** Expired */
            expired: boolean;
            /** Stale */
            stale: boolean;
            /** Pending */
            pending: boolean;
        };
        /** AuditView */
        AuditView: {
            /** Id */
            id: string;
            /** Actor Id */
            actor_id: string | null;
            /** Workspace Id */
            workspace_id: string | null;
            /** Resource Id */
            resource_id: string | null;
            /** Action */
            action: string;
            /** Result */
            result: string;
            /** Created At */
            created_at: number;
            /** Request Id */
            request_id: string | null;
            /** Changes */
            changes: {
                [key: string]: unknown;
            } | null;
        };
        /** Authorization */
        Authorization: {
            /**
             * Cookie
             * Format: password
             */
            cookie: string;
            /** Label */
            label?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** AuthorizationError */
        AuthorizationError: {
            /** Detail */
            detail: string;
            /** Code */
            code?: ("invalid_session_cookie" | "cookie_account_mismatch") | null;
        };
        /** Bootstrap */
        Bootstrap: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "server" | "local";
            /** Initialized */
            initialized: boolean;
            /** Api Version */
            api_version: number;
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
            /**
             * App Version
             * @default 0.0.1
             */
            app_version: string;
        };
        /** Csrf */
        Csrf: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** Cycle */
        Cycle: {
            /** Start */
            start?: string | null;
            /** Reset At */
            reset_at?: string | null;
            /** Days Left */
            days_left?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** DetailGroup */
        DetailGroup: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Spend Usd */
            spend_usd: number;
            /** Total Tokens */
            total_tokens: number;
            /** Models */
            models: components["schemas"]["ModelUsage"][];
        };
        /** DetailTotals */
        DetailTotals: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Cache Write Tokens
             * @default 0
             */
            cache_write_tokens: number;
            /**
             * Cache Read Tokens
             * @default 0
             */
            cache_read_tokens: number;
            /** Spend Usd */
            spend_usd: number;
            /** Total Tokens */
            total_tokens: number;
            /** Model Count */
            model_count: number;
        } & {
            [key: string]: unknown;
        };
        /** DetailView */
        DetailView: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Cycle Start */
            cycle_start: string;
            /** Fetched At */
            fetched_at: string;
            /** Groups */
            groups: components["schemas"]["DetailGroup"][];
            totals: components["schemas"]["DetailTotals"];
        };
        /** DeviceApproval */
        DeviceApproval: {
            /** Code Challenge */
            code_challenge: string;
            /** State */
            state: string;
            /** Callback */
            callback: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Device Name */
            device_name: string;
        };
        /** DeviceApproved */
        DeviceApproved: {
            /** Callback Url */
            callback_url: string;
        };
        /** DeviceConsume */
        DeviceConsume: {
            /**
             * Token
             * Format: password
             */
            token: string;
        };
        /** DeviceDelivery */
        DeviceDelivery: {
            /** Ticket Id */
            ticket_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Account Id */
            account_id: string;
            /** Expires At */
            expires_at: number;
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Email */
            email: string;
            /** Subject */
            subject: string;
        };
        /** DeviceExchange */
        DeviceExchange: {
            /**
             * Code
             * Format: password
             */
            code: string;
            /**
             * Verifier
             * Format: password
             */
            verifier: string;
            /** Callback */
            callback: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
        };
        /** DeviceLogin */
        DeviceLogin: {
            /** Token */
            token: string;
            /** Session Id */
            session_id: string;
            /** Expires At */
            expires_at: number;
        };
        /** DeviceResult */
        DeviceResult: {
            /**
             * Result
             * @enum {string}
             */
            result: "success" | "failure" | "cancelled";
        };
        /** GrantChange */
        GrantChange: {
            /** Level */
            level: string;
        };
        /** GrantView */
        GrantView: {
            /** User Id */
            user_id: string;
            /**
             * Level
             * @enum {string}
             */
            level: "view" | "use";
        };
        /** Grok */
        Grok: {
            /** Remaining Pct */
            remaining_pct?: number | null;
            /** Reset At */
            reset_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Api Version */
            api_version: number;
        };
        /** InstallUpdate */
        InstallUpdate: {
            /** Version */
            version: string;
        };
        /** InvitationIssued */
        InvitationIssued: {
            /** Id */
            id: string;
            /** Token */
            token: string;
            /** Expires At */
            expires_at: number;
        };
        /** InvitationView */
        InvitationView: {
            /** Id */
            id: string;
            /** Login */
            login: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member" | "viewer";
            /** Expires At */
            expires_at: number;
        };
        /** Invite */
        Invite: {
            /** Login */
            login: string;
            /** Role */
            role: string;
        };
        /** Joined */
        Joined: {
            /** User Id */
            user_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** Login */
        Login: {
            /** Login */
            login: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** LoginResult */
        LoginResult: {
            /** Csrf Token */
            csrf_token: string;
            /** Expires At */
            expires_at: number;
        };
        /** ManualConsume */
        ManualConsume: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "macos" | "windows";
            /**
             * Token
             * Format: password
             */
            token: string;
        };
        /** ManualScript */
        ManualScript: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "macos" | "windows";
            /** Command */
            command: string;
            /** Expires At */
            expires_at: number;
            /** Script */
            script: string;
        };
        /** Me */
        Me: {
            /** Id */
            id: string;
            /** Login */
            login: string;
            /** Instance Admin */
            instance_admin: boolean;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceView"][];
        };
        /** MemberView */
        MemberView: {
            /** Id */
            id: string;
            /** Login */
            login: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "member" | "viewer";
            /** Active */
            active: boolean;
        };
        /** ModelUsage */
        ModelUsage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Cache Write Tokens
             * @default 0
             */
            cache_write_tokens: number;
            /**
             * Cache Read Tokens
             * @default 0
             */
            cache_read_tokens: number;
            /** Model */
            model: string;
            /** Group */
            group: string;
            /** Total Tokens */
            total_tokens: number;
            /** Spend Usd */
            spend_usd: number;
            /** Spend Cents */
            spend_cents: number;
        } & {
            [key: string]: unknown;
        };
        /** OnDemand */
        OnDemand: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Used Usd */
            used_usd?: number | null;
            /** Limit Usd */
            limit_usd?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** OwnerChange */
        OwnerChange: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** PasswordChange */
        PasswordChange: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            /**
             * New Password
             * Format: password
             */
            new_password: string;
        };
        /** Plan */
        Plan: {
            /** Name */
            name?: string | null;
            /** Included Usd */
            included_usd?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** QuotaReference */
        QuotaReference: {
            /** Cycle Start */
            cycle_start: string;
            /** Cursor Models */
            cursor_models?: number | null;
            /** Other Models */
            other_models?: number | null;
            /** Overall */
            overall?: number | null;
        };
        /** QuotaSlot */
        QuotaSlot: {
            /** Used Pct */
            used_pct?: number | null;
            /** Remaining Pct */
            remaining_pct?: number | null;
            /** Limit Usd */
            limit_usd?: number | null;
            /** Used Usd */
            used_usd?: number | null;
            /** Remaining Usd */
            remaining_usd?: number | null;
            /**
             * Limit Inferred
             * @default false
             */
            limit_inferred: boolean;
            /** Limit Source */
            limit_source?: ("history" | "plan" | "reference") | null;
        } & {
            [key: string]: unknown;
        };
        /** ReleaseInfo */
        ReleaseInfo: {
            /** Current Version */
            current_version: string;
            /** Latest Version */
            latest_version: string | null;
            /** Available */
            available: boolean;
            /** Installable */
            installable: boolean;
            /** Notes */
            notes: string;
            /** Release Url */
            release_url: string;
            /** Published At */
            published_at: string | null;
        };
        /** RoleChange */
        RoleChange: {
            /** Role */
            role: string;
        };
        /** SessionView */
        SessionView: {
            /** Id */
            id: string;
            /** Created At */
            created_at: number;
            /** Expires At */
            expires_at: number;
            /** Current */
            current: boolean;
            /**
             * Kind
             * @default web
             * @enum {string}
             */
            kind: "web" | "device";
            /** Device Id */
            device_id?: string | null;
            /** Device Name */
            device_name?: string | null;
        };
        /** Spend */
        Spend: {
            /** Total */
            total?: number | null;
            /** From Included */
            from_included?: number | null;
            /** From Bonus */
            from_bonus?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** SwitchCommand */
        SwitchCommand: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "macos" | "windows";
            /** Command */
            command: string;
            /** Expires At */
            expires_at: number;
        };
        /** SwitchIssued */
        SwitchIssued: {
            /** Token */
            token: string;
            /** Expires At */
            expires_at: number;
        };
        /** SwitchPlatform */
        SwitchPlatform: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "macos" | "windows";
        };
        /** UpdateStatus */
        UpdateStatus: {
            /** Enabled */
            enabled: boolean;
            /**
             * Stage
             * @enum {string}
             */
            stage: "idle" | "queued" | "downloading" | "verifying" | "backing_up" | "upgrading" | "restarting" | "rolling_back" | "complete" | "failed";
            /** Job Id */
            job_id: string | null;
            /** Version */
            version: string | null;
            /** Message */
            message: string | null;
        };
        /** Usage */
        Usage: {
            plan?: components["schemas"]["Plan"];
            cycle?: components["schemas"]["Cycle"];
            /** Quota */
            quota?: {
                [key: string]: components["schemas"]["QuotaSlot"];
            };
            grok_weekly?: components["schemas"]["Grok"] | null;
            /** Notice */
            notice?: string | null;
            spend_usd?: components["schemas"]["Spend"] | null;
            on_demand?: components["schemas"]["OnDemand"] | null;
        } & {
            [key: string]: unknown;
        };
        /** UserState */
        UserState: {
            /** Active */
            active: boolean;
        };
        /** UserView */
        UserView: {
            /** Id */
            id: string;
            /** Login */
            login: string;
            /** Active */
            active: boolean;
            /** Instance Admin */
            instance_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceCapabilities */
        WorkspaceCapabilities: {
            /** Manage Accounts */
            manage_accounts: boolean;
            /** Manage Members */
            manage_members: boolean;
            /** Manage Admins */
            manage_admins: boolean;
            /** Transfer Owner */
            transfer_owner: boolean;
            /** Delete */
            delete: boolean;
            /** Audit */
            audit: boolean;
            /** Export Credentials */
            export_credentials: boolean;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
        };
        /** WorkspaceCreated */
        WorkspaceCreated: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "personal" | "team";
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "member" | "viewer";
        };
        /** WorkspaceView */
        WorkspaceView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "personal" | "team";
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "member" | "viewer";
            capabilities: components["schemas"]["WorkspaceCapabilities"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_api_v1_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
        };
    };
    check_updates_api_v1_updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseInfo"];
                };
            };
        };
    };
    update_status_api_v1_instance_update_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
        };
    };
    install_update_api_v1_instance_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    csrf_api_v1_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    password_api_v1_auth_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_api_v1_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"][];
                };
            };
        };
    };
    revoke_session_api_v1_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_device_api_v1_auth_devices_authorize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceApproval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceApproved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_device_api_v1_auth_devices_exchange_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceExchange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLogin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    devices_api_v1_auth_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"][];
                };
            };
        };
    };
    revoke_device_api_v1_auth_devices__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workspace_api_v1_workspaces__workspace_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_owner_api_v1_workspaces__workspace_id__owner_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    members_api_v1_workspaces__workspace_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    role_api_v1_workspaces__workspace_id__members__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_workspaces__workspace_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invitations_api_v1_workspaces__workspace_id__invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_api_v1_workspaces__workspace_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationIssued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_v1_workspaces__workspace_id__invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_api_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Joined"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accounts_api_v1_workspaces__workspace_id__accounts_get: {
        parameters: {
            query?: {
                q?: string;
                tag?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_account_api_v1_workspaces__workspace_id__accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Authorization"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationError"];
                };
            };
        };
    };
    account_api_v1_workspaces__workspace_id__accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_workspaces__workspace_id__accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_account_api_v1_workspaces__workspace_id__accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reauthorize_account_api_v1_workspaces__workspace_id__accounts__account_id__authorization_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Authorization"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationError"];
                };
            };
        };
    };
    refresh_api_v1_workspaces__workspace_id__accounts__account_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_workspaces__workspace_id__accounts__account_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grants_api_v1_workspaces__workspace_id__accounts__account_id__grants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_api_v1_workspaces__workspace_id__accounts__account_id__grants__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_grant_api_v1_workspaces__workspace_id__accounts__account_id__grants__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_audit_api_v1_workspaces__workspace_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_api_v1_instance_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"][];
                };
            };
        };
    };
    user_state_api_v1_instance_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserState"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instance_audit_api_v1_instance_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    manual_ticket_api_v1_workspaces__workspace_id__accounts__account_id__manual_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchIssued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_command_api_v1_workspaces__workspace_id__accounts__account_id__switch_command_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchPlatform"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchCommand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_download_api_v1_switch__token___platform__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                platform: "macos" | "windows";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_consume_api_v1_manual_switch_consume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualConsume"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualScript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_ticket_api_v1_workspaces__workspace_id__accounts__account_id__device_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchIssued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_consume_api_v1_device_switch_consume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceConsume"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDelivery"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    device_result_api_v1_device_switch__ticket_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceResult"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
